---
# tasks file for deploy_elk


- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_project_src }}/elasticsearch"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_project_src }}/logstash"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_project_src }}/kibana"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_project_src }}/logstash/conf.d"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_data_src }}/elasticsearch"
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_elk_data_src }}/elasticsearch/data"
    state: directory
    mode: '0777'
    owner: nobody
    group: nogroup

- name: copy a file elasticsearch.yml
  ansible.builtin.copy:
    src: elasticsearch.yml
    dest: "{{ deploy_elk_project_src }}/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_elk

- name: copy a file logstash.yml
  ansible.builtin.copy:
    src: logstash.yml
    dest: "{{ deploy_elk_project_src }}/logstash/logstash.yml"
    owner: root
    group: root
    mode: '0666'
    backup: true
  notify: restart_elk

- name: copy a file pipeline.conf
  ansible.builtin.copy:
    src: pipeline.conf
    dest: "{{ deploy_elk_project_src }}/logstash/conf.d/logstash.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_elk

- name: copy a file kibana.yml
  ansible.builtin.copy:
    src: kibana.yml
    dest: "{{ deploy_elk_project_src }}/kibana/kibana.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_elk

- name: template a file docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_elk_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_elk

- name: create and start elk
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_elk_project_src }}"
    state: present