---
# tasks file for deploy_nginx_exporter

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_nginx_exporter_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: template a file docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_nginx_exporter_project_src }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
    backup: true
  notify: restart_nginx_exporter

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_nginx_exporter_project_src }}"
    state: present