---
# tasks file for deploy_cadvisor

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_cadvisor_project_src }}"
    state: directory
    mode: '0644'
    owner: root
    group: root

- name: template a file docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ deploy_cadvisor_project_src }}/docker-compose.yml"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_cadvisor

- name: create and start cadvisor
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_cadvisor_project_src }}"
    state: present