---
# tasks file for deploy_node_exporter

- name: create a directory
  ansible.builtin.file:
    path: "{{ deploy_node_exporter_project_src }}"
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: copy a file docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ deploy_node_exporter_project_src }}"/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: restart_node_exporter

- name: create and start node_exporter
  community.docker.docker_compose_v2:
    project_src: "{{ deploy_node_exporter_project_src }}"
    state: present